// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.u64().name("user_id"),
  primaryEmail: __t.string().name("primary_email"),
  displayName: __t.string().name("display_name"),
  pictureUrl: __t.option(__t.string()).name("picture_url"),
  isAdmin: __t.bool().name("is_admin"),
});
