// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { SituationState } from "./types";

export default __t.row({
  cardId: __t.u64().primaryKey().name("card_id"),
  boardId: __t.u64().name("board_id"),
  get state() {
    return SituationState;
  },
  endsAt: __t.option(__t.timestamp()).name("ends_at"),
});
