// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Board = __t.object("Board", {
  id: __t.u64(),
  name: __t.string(),
  owner: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Board = __Infer<typeof Board>;

export const BoardMember = __t.object("BoardMember", {
  id: __t.u64(),
  boardId: __t.u64(),
  userId: __t.u64(),
  get role() {
    return MemberRole;
  },
});
export type BoardMember = __Infer<typeof BoardMember>;

export const Card = __t.object("Card", {
  id: __t.u64(),
  boardId: __t.u64(),
  defId: __t.string(),
  get location() {
    return Location;
  },
});
export type Card = __Infer<typeof Card>;

export const CardDef = __t.object("CardDef", {
  defId: __t.string(),
  name: __t.string(),
  category: __t.string(),
  isVerb: __t.bool(),
  reusable: __t.bool(),
  outputCap: __t.u32(),
});
export type CardDef = __Infer<typeof CardDef>;

export const CardHistory = __t.object("CardHistory", {
  id: __t.u64(),
  boardId: __t.u64(),
  defId: __t.string(),
  count: __t.u64(),
});
export type CardHistory = __Infer<typeof CardHistory>;

export const Identity = __t.object("Identity", {
  id: __t.identity(),
  userId: __t.u64(),
  get provider() {
    return IdentityProvider;
  },
  linkedAt: __t.timestamp(),
});
export type Identity = __Infer<typeof Identity>;

// The tagged union or sum type for the algebraic type `IdentityProvider`.
export const IdentityProvider = __t.enum("IdentityProvider", {
  Google: __t.unit(),
  Spacetime: __t.unit(),
});
export type IdentityProvider = __Infer<typeof IdentityProvider>;

// The tagged union or sum type for the algebraic type `Location`.
export const Location = __t.enum("Location", {
  get Tabletop() {
    return Tabletop;
  },
  get Slotted() {
    return Slotted;
  },
  get Output() {
    return Output;
  },
});
export type Location = __Infer<typeof Location>;

export const MeRow = __t.object("MeRow", {
  userId: __t.u64(),
  primaryEmail: __t.string(),
  displayName: __t.string(),
  pictureUrl: __t.option(__t.string()),
  isAdmin: __t.bool(),
});
export type MeRow = __Infer<typeof MeRow>;

export const MeView = __t.object("MeView", {});
export type MeView = __Infer<typeof MeView>;

// The tagged union or sum type for the algebraic type `MemberRole`.
export const MemberRole = __t.enum("MemberRole", {
  Player: __t.unit(),
  Spectator: __t.unit(),
});
export type MemberRole = __Infer<typeof MemberRole>;

export const MyBoardMembers = __t.object("MyBoardMembers", {});
export type MyBoardMembers = __Infer<typeof MyBoardMembers>;

export const MyBoards = __t.object("MyBoards", {});
export type MyBoards = __Infer<typeof MyBoards>;

export const MyCardHistory = __t.object("MyCardHistory", {});
export type MyCardHistory = __Infer<typeof MyCardHistory>;

export const MyCards = __t.object("MyCards", {});
export type MyCards = __Infer<typeof MyCards>;

export const MyPlayers = __t.object("MyPlayers", {});
export type MyPlayers = __Infer<typeof MyPlayers>;

export const MySituations = __t.object("MySituations", {});
export type MySituations = __Infer<typeof MySituations>;

export const Output = __t.object("Output", {
  verbCardId: __t.u64(),
});
export type Output = __Infer<typeof Output>;

export const Situation = __t.object("Situation", {
  cardId: __t.u64(),
  boardId: __t.u64(),
  get state() {
    return SituationState;
  },
  endsAt: __t.option(__t.timestamp()),
});
export type Situation = __Infer<typeof Situation>;

// The tagged union or sum type for the algebraic type `SituationState`.
export const SituationState = __t.enum("SituationState", {
  Assembling: __t.unit(),
  Ongoing: __t.unit(),
  Stalled: __t.unit(),
});
export type SituationState = __Infer<typeof SituationState>;

export const SituationTimer = __t.object("SituationTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  verbCardId: __t.u64(),
});
export type SituationTimer = __Infer<typeof SituationTimer>;

export const SlotDef = __t.object("SlotDef", {
  id: __t.u64(),
  defId: __t.string(),
  slotIndex: __t.u32(),
  accepts: __t.array(__t.string()),
  required: __t.bool(),
});
export type SlotDef = __Infer<typeof SlotDef>;

export const Slotted = __t.object("Slotted", {
  verbCardId: __t.u64(),
  slotIndex: __t.u32(),
});
export type Slotted = __Infer<typeof Slotted>;

export const Tabletop = __t.object("Tabletop", {
  x: __t.f32(),
  y: __t.f32(),
});
export type Tabletop = __Infer<typeof Tabletop>;

export const User = __t.object("User", {
  id: __t.u64(),
  primaryEmail: __t.string(),
  displayName: __t.string(),
  pictureUrl: __t.option(__t.string()),
  isAdmin: __t.bool(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;
