// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BootstrapFirstAdminReducer from "../bootstrap_first_admin_reducer";
import CollectAndSlotReducer from "../collect_and_slot_reducer";
import MoveCardReducer from "../move_card_reducer";
import NewGameReducer from "../new_game_reducer";
import SlotCardReducer from "../slot_card_reducer";

export type BootstrapFirstAdminParams = __Infer<
  typeof BootstrapFirstAdminReducer
>;
export type CollectAndSlotParams = __Infer<typeof CollectAndSlotReducer>;
export type MoveCardParams = __Infer<typeof MoveCardReducer>;
export type NewGameParams = __Infer<typeof NewGameReducer>;
export type SlotCardParams = __Infer<typeof SlotCardReducer>;
