// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AutoLayoutReducer from "../auto_layout_reducer";
import BeginLinkReducer from "../begin_link_reducer";
import ClaimLinkReducer from "../claim_link_reducer";
import CollectAndSlotReducer from "../collect_and_slot_reducer";
import DeleteMyAccountReducer from "../delete_my_account_reducer";
import DevGrantReducer from "../dev_grant_reducer";
import DiscardBoardReducer from "../discard_board_reducer";
import HouseCardReducer from "../house_card_reducer";
import MarkAchievementSeenReducer from "../mark_achievement_seen_reducer";
import MoveCardReducer from "../move_card_reducer";
import NewGameReducer from "../new_game_reducer";
import RegisterAdminReducer from "../register_admin_reducer";
import RelayoutBoardReducer from "../relayout_board_reducer";
import ReseedCatalogueReducer from "../reseed_catalogue_reducer";
import SlotCardReducer from "../slot_card_reducer";
import UnhouseCardReducer from "../unhouse_card_reducer";

export type AutoLayoutParams = __Infer<typeof AutoLayoutReducer>;
export type BeginLinkParams = __Infer<typeof BeginLinkReducer>;
export type ClaimLinkParams = __Infer<typeof ClaimLinkReducer>;
export type CollectAndSlotParams = __Infer<typeof CollectAndSlotReducer>;
export type DeleteMyAccountParams = __Infer<typeof DeleteMyAccountReducer>;
export type DevGrantParams = __Infer<typeof DevGrantReducer>;
export type DiscardBoardParams = __Infer<typeof DiscardBoardReducer>;
export type HouseCardParams = __Infer<typeof HouseCardReducer>;
export type MarkAchievementSeenParams = __Infer<
  typeof MarkAchievementSeenReducer
>;
export type MoveCardParams = __Infer<typeof MoveCardReducer>;
export type NewGameParams = __Infer<typeof NewGameReducer>;
export type RegisterAdminParams = __Infer<typeof RegisterAdminReducer>;
export type RelayoutBoardParams = __Infer<typeof RelayoutBoardReducer>;
export type ReseedCatalogueParams = __Infer<typeof ReseedCatalogueReducer>;
export type SlotCardParams = __Infer<typeof SlotCardReducer>;
export type UnhouseCardParams = __Infer<typeof UnhouseCardReducer>;
